### ISSUE TITLE
This plugin cant work in ionic app ?

### ISSUE THREAD

**Issue by trandangninh** [Leaflet/Leaflet.VectorGrid#123]
I am using ionic version 1, after testing, I saw that this plugin can only work on web browser, but it didnt in my ionic app (in iOS), do you have any solutions for this ?

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
