### ISSUE TITLE
Implement mouse interaction event handlers

### ISSUE THREAD

**Issue by rishabhjain30** [Leaflet/Leaflet.VectorGrid#3]
The features can be really useful. Do you have a plan to implement it? Will love to work on it.

P. S. Would also love to work on implementing point zoom. We can do it similar to https://github.com/SpatialServer/Leaflet.MapboxVectorTile where each marker is converted to an actual leaflet object.

**Comment by IvanSanchez** [comment]
So implementing mouse interactions (`click`, `mousemove`, `mouseover` and so on) is not trivial but should be straightforward:

* [ ] Decorate `L.GridLayer.getEvents()` so that the `click` and `mousemove` (etc) events are handled by `_onClick()` and `_onMouseMove()` (etc) methods (besides the default `L.GridLayer` DOM event handlers).
* [ ] In `_onClick`, detect which tile was clicked, delegate detection of feature clicked to the tile renderer
* [ ] In the case of `L.Renderer.Canvas.Tile`, delegate the click to the appropiate tile renderer, call its `_onClick` method.
* [ ] In the case of `L.Renderer.SVG.Tile`, delegate the click to the appropiate SVG DOM element.
* [ ] Delegate `_onMouseMove` to the renderers in a similar fashion.

**Comment by IvanSanchez** [comment]
@rishabhjain30 I don't care if «the features can be useful». **Describe** the desired behaviour instead: spartan bug reports / feature requests are usually received and handled better.

**Comment by IvanSanchez** [comment]
Alternatively, just:
* [ ] Use Leaflet 1.0.0's `L.Evented.addEventParent` to make tile renderers delegate events back to the VectorGrid
* [ ] Pass `this` to the tile renderer constructor (`this.options.rendererFactory`)

**Comment by IvanSanchez** [comment]
Implemented by #22
