### ISSUE TITLE
Error loading geojson points fetures

### ISSUE THREAD

**Issue by brunosmartin** [Leaflet/Leaflet.VectorGrid#32]
I'm trying to use L.vectorGrid.slicer(points.geojson) but I get "TypeError: invalid 'in' operand coord" in my console. 

The error is in line 208 of Leaflet.VectorGrid.js file (https://github.com/Leaflet/Leaflet.VectorGrid/blob/61cf2d1a721af9b5be2d026df64ee4177f906ecd/src/Leaflet.VectorGrid.js#L208)

Sorry for this short report, but the due date is coming... 

if you need more information, please let me know...

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by haoliangyu** [comment]
I am having the same issue. Please have a look at this [bug demo](http://plnkr.co/edit/oJfmY9GaiPDp2ORJQEVr?p=preview) @IvanSanchez. It may take a few seconds for the error message to appear at the console.

**Comment by perliedman** [comment]
@haoliangyu thanks for the example! I think this might be because GeoJSON features store points differently from Vector Tiles, and the current implementation has been written with Vector Tiles in mind.

Will have to check this out in more detail, but I think it should be straight forward to add some conditional when extracting the coordinate in `_makeFeatureParts`. A PR would be very welcome!
