### ISSUE TITLE
Nothing displayed with L.Canvas.Tile

### ISSUE THREAD

**Issue by glandais** [Leaflet/Leaflet.VectorGrid#51]
Using leaflet 1.0.2

Looks like _drawing is undefined in L.Canvas

Suggested : _draw() in addTo

**Comment by perliedman** [comment]
Hi, I believe this problem does not exist if you're using latest VectorGrid from `master`, since it defines `_drawing`: https://github.com/Leaflet/Leaflet.VectorGrid/blob/master/src/Leaflet.Renderer.Canvas.Tile.js#L15

Earlier versions (and unfortunately the latest released version at the time of writing) does not support Leaflet 1.0.2 for this reason.

**Comment by reyemtm** [comment]
Would be nice then to add supported leaflet versions in the read me.
