### ISSUE TITLE
Rendering issue when a line cross a tile

### ISSUE THREAD

**Issue by vmeurisse** [Leaflet/Leaflet.VectorGrid#64]
When a line cross a tile limit, there might be visual issues
![image](https://cloud.githubusercontent.com/assets/1368138/22261271/8b41439a-e26c-11e6-853b-3ec8430562ca.png)

Url to reproduce
https://cdn.rawgit.com/vmeurisse/57314572b95621cf24f5407522855e08/raw/a77b3bfe70003721ddf9da0c807be2e017829e6a/vectorLayerLine.html

**Comment by perliedman** [comment]
This is more or less the same issue as #63, so copying my response for that issue here as well:

For points to be rendered correctly when close to or at the tile boundary, they must also be present in the adjancent tiles' data.

As can be seen in the screenshot, the rendering is clipped at the tile border. If the point would also be present in adjacent tiles, each tile would render a clipped version of the point, but the union of these clipped renderings would be the complete symbol (circle).

To accomplish this, the tiles need to have some overlap, and the amount of overlap required actually depends on the size of the point symbolizer.

You can read more about the reasoning behind this in Mapbox's Vector Tile specification: https://www.mapbox.com/vector-tiles/specification/#clipping
