### ISSUE TITLE
Detection of features at pointer position in Firefox vs. Chrome

### ISSUE THREAD

**Issue by MrSnyder** [Leaflet/Leaflet.VectorGrid#90]
Thank you for this great project, it's working very well for me.

I am experiencing one issue, though. When clicking (or mouse-overing) on an interactive vector tile layer, the detection of features at the pointer position works perfect in Firefox. However, in Chrome (and Edge / IE 11 with fetch-polyfill) often neighbouring features are detected instead of the one that should actually be at the mouse position.

Is this a known problem?

Setup:

- Leaflet.VectorGrid v1.2.0
- Leaflet 1.03
+ fetch-polyfill to get older browsers working

Tested browsers:

- Firefox/Iceweasel 38.5 (Debian 8.0, AMD64)
- Chrome latest (Debian 8.0, AMD64)
- Edge (Windows 10, AMD64)
- IE 7 (Windows 10, AMD64)

P.S.: I briefly tried with Leaflet.VectorGrid master as well, but the click event doesn't seem to work currently...

**Comment by perliedman** [comment]
I think what you're seeing might be a problem with Leaflet's [`_clickTolerance`](https://github.com/Leaflet/Leaflet/blob/49213551953067aa70c3c3d2e74a6c5431a896c5/src/layer/vector/Path.js#L138): when touch support is enabled, which it always is in recent versions of Chrome, it will use a large tolerance, to make it easier to hit things. This has the unfortunate side effect that you sometimes hit the wrong feature, since they aren't prioritized.

So, assuming this is the problem you're seeing, this is actually a Leaflet issue when using the canvas renderer, and not specific to Leaflet.VectorGrid.

**Comment by MrSnyder** [comment]
Yep, you're right

Thank you for pointing this out.
