### ISSUE TITLE
Nothing displayed when usind CRS EPSG4326

### ISSUE THREAD

**Issue by tylkomat** [Leaflet/Leaflet.VectorGrid#92]
I created an Example at https://github.com/tylkomat/leaflet-vectorgrid-epsg4326
Just clone an run with your favourite webserver, I was using `autoreload-server`.

When loaded normally via `L.geoJSON(...).addTo(map)` the map is properly displayed.

**Comment by perliedman** [comment]
Hi there,
I think the problem is that `slicer`'s underlying library, [geojson-vt](https://github.com/mapbox/geojson-vt) is hardwired to use EPSG:3857 (Spherical Mercator, Leaflet's default projection), see https://github.com/mapbox/geojson-vt/blob/master/src/convert.js#L94. This means it essentially non-compatible with other projections.

@IvanSanchez perhaps we should see to that `slicer` throws or at least writes a warning when you try to add it to a map with another projection?

**Comment by perliedman** [comment]
Related: https://github.com/mapbox/geojson-vt/issues/57
